# Dockerfile.dev (para desarrollo)
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --force

# Copiamos todo el código (React/Vite)
COPY . .

# Exponemos el puerto que usa Vite
EXPOSE 5173

# Comandos de desarollo (con hot reload)
CMD [ "npm", "run", "dev", "--", "--host" ]
